// <auto-generated />
using System;
using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Data.Migrations
{
    [DbContext(typeof(TPI_DbContext))]
    [Migration("20241124212841_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Datos_usuario", b =>
                {
                    b.Property<int>("usuarioID")
                        .HasColumnType("int");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("codigoArea")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("usuarioID");

                    b.ToTable("Datos_usuario");
                });

            modelBuilder.Entity("Core.Entities.Oferta", b =>
                {
                    b.Property<int>("ofertaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ofertaID"));

                    b.Property<int>("estadoOferta")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaOferta")
                        .HasColumnType("datetime2");

                    b.Property<float>("montoOferta")
                        .HasColumnType("real");

                    b.Property<int?>("productoID")
                        .HasColumnType("int");

                    b.Property<int?>("usuarioID")
                        .HasColumnType("int");

                    b.HasKey("ofertaID");

                    b.HasIndex("productoID");

                    b.HasIndex("usuarioID");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("Core.Entities.Producto", b =>
                {
                    b.Property<int>("productoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productoID"));

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estadoProducto")
                        .HasColumnType("int");

                    b.Property<int>("estadoSolicitud")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("metodoEntrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precioBase")
                        .HasColumnType("float");

                    b.Property<int?>("subastaID")
                        .HasColumnType("int");

                    b.Property<int?>("usuarioID")
                        .HasColumnType("int");

                    b.HasKey("productoID");

                    b.HasIndex("subastaID");

                    b.HasIndex("usuarioID");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Core.Entities.Subasta", b =>
                {
                    b.Property<int>("subastaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("subastaID"));

                    b.Property<int>("estadoSubasta")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaFinalizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("metodosdePago")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subastaID");

                    b.ToTable("Subastas");
                });

            modelBuilder.Entity("Core.Entities.Usuario", b =>
                {
                    b.Property<int>("usuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usuarioID"));

                    b.Property<byte[]>("HashPassword")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("usuarioID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Core.Entities.Datos_usuario", b =>
                {
                    b.HasOne("Core.Entities.Usuario", "Usuario")
                        .WithOne("DatosUsuario")
                        .HasForeignKey("Core.Entities.Datos_usuario", "usuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Core.Entities.Oferta", b =>
                {
                    b.HasOne("Core.Entities.Producto", "producto")
                        .WithMany("listaOfertas")
                        .HasForeignKey("productoID");

                    b.HasOne("Core.Entities.Usuario", "usuario")
                        .WithMany("listaOfertas")
                        .HasForeignKey("usuarioID");

                    b.Navigation("producto");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Core.Entities.Producto", b =>
                {
                    b.HasOne("Core.Entities.Subasta", "Subasta")
                        .WithMany("listaProductos")
                        .HasForeignKey("subastaID");

                    b.HasOne("Core.Entities.Usuario", "Usuario")
                        .WithMany("listaProductos")
                        .HasForeignKey("usuarioID");

                    b.Navigation("Subasta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Core.Entities.Producto", b =>
                {
                    b.Navigation("listaOfertas");
                });

            modelBuilder.Entity("Core.Entities.Subasta", b =>
                {
                    b.Navigation("listaProductos");
                });

            modelBuilder.Entity("Core.Entities.Usuario", b =>
                {
                    b.Navigation("DatosUsuario");

                    b.Navigation("listaOfertas");

                    b.Navigation("listaProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
